apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: caw0rr8j2-python
  janus-idp.io/tekton: caw0rr8j2-python
  backstage.io/kubernetes-id: caw0rr8j2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: caw0rr8j2-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
